### ISSUE TITLE
Peek

### ISSUE THREAD

**Issue by maxim** [costaraphael/cspex#2]
Hey, this is pretty cool, I actually have a use case for it, but there is one tiny thing missing for my use case. I have 4 processes that would be consuming a single channel in parallel, but each needs to be able to `peek` the value before `get`-ing it, and only `get` if it satisfies a condition.  Think it's something worth adding?

**Comment by costaraphael** [comment]
Hey @maxim!

After we talked on slack a few days ago, I started to look at the code in order to implement the "filtered get". The thing is, it was a mess :smile: 

So did a major refactor in the lib, made a few breaking changes for the best (the functions `Channel.member?/2` and `Channel.count/1` were removed and if you try to use the `Enum` variants in the channel it will raise a `RuntimeError`) and fixed some problems and leaks.

All of this allowed me to create some extra functions, like `Channel.from_enumerables/1` and `Channel.partition/2`.

Based on our discussion, the problem you have is that you want to distribute the events of the channel into many different workers, so each worker only gets what it wants, right?

So, one of the created functions (`CSP.Channel.partition/3`) might solve the problem:

```elixir
iex> main_channel = Channel.new()
iex> partitions = Channel.partition(main_channel, 1..4, & &1.partition)
%{
  1 => #Channel<ref=#PID<0.154.0>, state=open>,
  2 => #Channel<ref=#PID<0.155.0>, state=open>,
  3 => #Channel<ref=#PID<0.156.0>, state=open>,
  4 => #Channel<ref=#PID<0.157.0>, state=open>
}
```

This way you can pass a channel to each worker, feed elements into the main channel and they will get routed to one of the workers based on the routing function.

This version is already available in hex as `2.0.0-beta`.

Does this solve the problem?

**Comment by maxim** [comment]
Hey @costaraphael - this is amazing, looks like you've done a ton of work. I kinda envy how much you must've learned working on this. This lib is great and I'm sure I'm not the last person to find a use case for it (and this isn't my last project either). In my specific case I managed to work out a similar solution with GenStage on the day after we talked (tight deadline), but I'll be looking out for more use cases going forward.

**Comment by costaraphael** [comment]
Don't worry man, with GenStage and Flow around, this library was never intended to be a smash hit. I have even considered adding a disclaimer to the README asking people to use GenStage instead. :joy: 

It was fun to get my hands dirty revamping the code and fixing some bugs, but that's about it. :slightly_smiling_face: 

Since the possible use case is contained in the newly defined functions, I'll close this issue.
